### ISSUE TITLE
PDF-Documentation fault

### ISSUE THREAD

**Issue by BMuXBeats** [codygeary/CVfunk-Modules#18]
The URL ind Readme.md to your User'S Manual opens a new page, but with an empty PDF document.

PDF file seems to be defect.

**Comment by codygeary** [comment]
Thanks for the heads up. Are you trying to view it on iOS? I had another user say the pdf didn't render properly in the github window. Try downloading the pdf and viewing it. I think it's a problem with github and not the pdf.

**Comment by BMuXBeats** [comment]
_Try downloading the pdf and viewing it._
I've tried this out, too.

_I think it's a problem with github and not the pdf._
Unfortunately not. I'm working under LINUX and tried to open the PDF as well as in Okular and Firefox.
In both viewers the same result: A faulty document. In Okular it seems like a sgml text and in Firefox the document is completely empty.

**Comment by codygeary** [comment]
Hmm, maybe it's an incompatibility with your pdf viewer. I'll try to rebuild the pdf as a pdf-a with more compatibility options enabled tomorrow.
Thanks again for letting me know.

**Comment by BMuXBeats** [comment]
I'm sure, it's not.
Today I've tested it under WIN11Pro with Mozilla Firefox (Version 127.0) and SumatraPDF (V 3.5.2 64-bit) and Acrobat Reader (Version 2024.002.20857 64-bit).
Always the same faulty result:
In Adobe Reader and SumatraPDF an error message comes up while opening the PDF. Mozilla Firefox display an empty document.

**Comment by codygeary** [comment]
Try it again. I just updated the PDF with better backwards compatibility down to Acrobat 5.  I have no idea why it wasn't working for you, I tested it on several platforms with no issue... and PDF is supposed to just work. Hope it fixes it!

**Comment by BMuXBeats** [comment]
I've tried it and it works fine, by now.

BUT: Not if I download it with a "save as..." from the link to the manual in your README.md
If I want to download the file this way, it will be saved as an html document.

The one and only way to get this as a real PDF is to navigate to the URL https://github.com/codygeary/CVfunk-Modules/blob/main/img/CV_funk_Manual.pdf and then download the document via the "..." button in the top right corner of the webpage and clicking there "download" (Section raw file content).

Looks for me that it has something to do with the correct MIME type at your github pages/sub pages and not with the document itself.

**Comment by codygeary** [comment]
Yeah, you have to click the 'download' button on git.. that's not something I can easily fix unless I host the PDF file elsewhere.  But at least it opens for you now!  :-)

Thanks again for the bug report. Being able to read the manual is pretty useful, so it's good if it's compatible with every platform out there.
