### ISSUE TITLE
Output stuck at 5V in Pressed Duck

### ISSUE THREAD

**Issue by freesurfacemodules** [codygeary/CVfunk-Modules#22]
Encountered a bug where moving inputs caused the output to be stuck at 5V (possibly due to internal NaN or inf?). It was triggered by swapping my inputs like so:

![Rack_0q3YEdODSV](https://github.com/user-attachments/assets/f4e9a532-d998-498b-873e-95ea65bb5a42)
![Rack_vAnuXrvh1r](https://github.com/user-attachments/assets/88650444-c5ca-4d16-ae93-8e2be451257f)

Hopefully this is sufficient for repro

**Comment by codygeary** [comment]
Thanks!  I'll look into it.

I have a couple more questions: 
Does reloading the patch solve the problem? Or does it require deleting and replacing the module to clear the DC?

Also, are you using the very latest v2.0.8.1? I tried to address this issue in the most recent patch, adding some extra div/zero checks. So if it's not fixed, then I need to go digging some more to see what's causing this problem.

Lastly, what platform are you on? As often is the case, these bugs can be platform specific.

**Comment by freesurfacemodules** [comment]
Yes, reloading fixes it. I'm using the latest from the library, it says 2.0.8 in the right click menu. This is on Windows. I tried it again and wasn't able to reproduce after swapping inputs a few times, so perhaps I just got unlucky.

**Comment by codygeary** [comment]
Okay, well, another user had the same issue with 2.0.8, and I think I patched it in 2.0.8.1, but on the other hand I wasn't able to get this bug to occur. My opinion is that this shouldn't happen ever, even if you are unlucky! But without being able to reproduce it on my end it's been a bit of guesswork to try to figure out what's causing it. The inner workings of this mixer are a bit over-complicated... I'll keep at it, maybe I'll find another bug hiding in plain sight.

If you are brave, please try the latest binary and let me know if the bug happens again.

**Comment by codygeary** [comment]
I think I fixed this in the latest 2.0.9 build. I was finally able to reproduce the problem with an older build, and I can't seem to get it stuck with the newest one.  So I'm closing the issue. Please re-open it if you see the bug again!  :-)
Thanks again for the bug report.
