### ISSUE TITLE
Step Wave feature request.

### ISSUE THREAD

**Issue by ContemporaryInsanity** [codygeary/CVfunk-Modules#24]

**Comment by ContemporaryInsanity** [comment]
Would be really nice if we could drive this with a phase clock, no sync delays and could run backwards, portions etc.

**Comment by codygeary** [comment]
So I tried really hard, but this is way more challenging than I thought. The architecture of the module makes implementing the phasors very complex. I'll take a much bigger reworking of the internal logic to make it work. Sorry to disappoint!  I'll keep it in mind for the future though.
