### ISSUE TITLE
TRI DELAY, Taps I & II do not respond to pan and feedback knobs

### ISSUE THREAD

**Issue by alexgamma** [codygeary/CVfunk-Modules#26]
I'm on a MacBook Air 2020 with M1 Chip and macOS Ventural 13.6.6, using VCV Rack Free 2.5.2.

In TRI DELAY, Taps I & II do not respond to pan and feedback knobs.

<img width="794" alt="CV Funk TRI DELAY" src="https://github.com/user-attachments/assets/39565095-fda6-4261-967c-c8bcec37164c">

Thanks

**Comment by codygeary** [comment]
That's funny, I wonder what happened.  I can't seem to reproduce this bug on my M1. The bigger knob is supposed to be a global adjustment, and the attenuverters add/subtract from the master. Can you send me the patch file?
Maybe try the latest Nightly build also.

**Comment by alexgamma** [comment]
Hi Cody,

the patch is attached. It shows failure to respond to pan/fdb of Taps 1 & 2  (mixer channels 1 & 2, respectively).
BTW, I can replicate this also on my iMac 2020 Intel core i9 using macOS 13.6.6. Tap 3 always works fine.
Alex

￼

**Comment by codygeary** [comment]
Github doesn't keep attachments in the comments, so you'll have to give me a link, or just e-mail me directly.
But I think I finally figured out what is going wrong, although I'm not sure how to fix it immediately. I will work on it. Thanks again for your patience.

**Comment by codygeary** [comment]
Ah ha. I found the problem. Tap3 was writing over the outputs from Taps 1 and 2.
It was a little tricky fixing it because the after fixing the Taps, then the feedback levels had to be compensated. I might have to work on this some more, but for now there's a new update in the nightly builds.
Thanks again for noticing this.

**Comment by alexgamma** [comment]
Thanks!
