### ISSUE TITLE
Module browser problem

### ISSUE THREAD

**Issue by ContemporaryInsanity** [codygeary/CVfunk-Modules#8]
My module bowser set to last updated having installed your plugin.  Four modules render fine, then a whole lot of empty space followed by an incompletely rendered Ranges.  This is on linux.

![image](https://github.com/codygeary/CVfunk-Modules/assets/12547379/d06c7088-bc40-4a51-8b18-e95ceb3d1fe2)

**Comment by ContemporaryInsanity** [comment]
Still the same.

**Comment by ContemporaryInsanity** [comment]
Further, if I click on the huge blank space a module is instantiated but it is invisible, I confirmed its presence by right clicking, the menu appeared as expected.

**Comment by codygeary** [comment]
Okay. I tried another thing, and I found some hidden layers to delete. Maybe that is what caused it... I know I have the right method since the other modules seem to look fine, so I just did what I did for those and cross my fingers!

Thanks again for testing for me.

**Comment by codygeary** [comment]
What I think is happening is that VCV determines the module dimensions from the SVG file, and I guess depending on the platform it can interpret this differently?  So, hopefully by scrubbing the SVG like crazy I can get it to work for you too!

**Comment by ContemporaryInsanity** [comment]
Still the same, so there's definitely something different about the signals svg compared to the others (ranges possibly excepted).

**Comment by codygeary** [comment]
Okay. I think I got it this time. I had named the dark panels -dark, and called to them as -Dark in the cpp code. Apparently in my file system it's not case-sensitive so I never noticed.

**Comment by ContemporaryInsanity** [comment]
Sorted!  Ranges fine now too.

Congrats on a very interesting and polished first plugin.
